services:
  backend:
    build: .
    ports: 
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - dp

  db:
    image: postgres
    restart: always
    env_file:
      - .env.production
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
